- .buildpacks
- Procfile
- config/database.yml
- config/environments/production.rb
Sistemi dokku üzerinde deploy edebilmek için bu değişikliklere ihtiyaç duyulmaktadır.
> Dokku preparation

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/controllers/studies/articles_controller.rb
- app/controllers/studies/certifications_controller.rb
- app/controllers/studies/dashboard_controller.rb
- app/controllers/studies/projects_controller.rb
- app/helpers/apa_helper.rb
- app/jobs/yoksis/articles_create_job.rb
- app/models/academic_studies/article.rb
- app/models/academic_studies/certification.rb
- app/models/academic_studies/project.rb
- app/models/unit.rb
- app/models/user.rb
- app/views/layouts/shared/_sidebar.html.erb
- app/views/studies/articles/index.html.erb
- app/views/studies/dashboard/index.html.erb
- config/locales/layouts/shared/sidebar_en.yml
- config/locales/layouts/shared/sidebar_tr.yml
- config/locales/models/studies/en.yml
- config/locales/models/studies/tr.yml
- config/routes.rb
- db/migrate/20180713221157_add_articles_count_to_users.rb
- db/migrate/20180713222542_add_projects_count_to_users.rb
- db/migrate/20180713224006_add_timestamps_to_publishings.rb
- db/schema.rb
- lib/tasks/counter_cache/update_counter_cache.rake
- lib/tasks/yoksis/import_yoksis_country_codes.rake
> Academic studies

- app/assets/stylesheets/guest.scss
- app/views/layouts/guest.html.erb
> Guest template'ine dil değişikliği için bayrak ikonlarını ekle

- app/views/layouts/application.html.erb
Referans: https://getbootstrap.com/docs/4.0/utilities/display/
> toggler visible only on md

- .circleci/config.yml
- .circleci/parallel_workflow.yml
- .circleci/sequential_basic_workflow.yml
- Gemfile
Changed current flow from sequential to fan-in-fan-out.
Fixes #205 and explained in #205.
> Added new workflows to Circleci

- .envrc
- .rubocop.yml
- README.md
- Vagrantfile
- bin/paas
Vagrantfile'da iki sanal makine oldu. Geliştirme için kullanılacak konteynere "dev", dokku denemelerinin yapılacağı sanal makineye "paas" ismini verdim. Daha uygun bir isim aklınıza geliyorsa değiştirebilirim.
> add paas vm to Vagrantfile

- app/views/users/_addresses.html.erb
- config/routes.rb
- test/controllers/users_controller_test.rb
[#91](https://github.com/omu/nokul/issues/91) doğrulama için users_controller testi hazırlandı.
path_prefix için konu ile ilgili örneklerde gösterilen 'my' kullanıldı, uygun görülen başka bir isimle değiştirilebilir.
> Users controller test

- .circleci/config.yml
- .circleci/parallel_workflow.yml
- .circleci/sequential_basic_workflow.yml
- app/views/users/_addresses.html.erb
- config/routes.rb
> Revert "Fix cache keys of CircleCI"

- Gemfile
- Gemfile.lock
- README.md
- docs/CONTRIBUTING.md
- docs/development/app-upgrade.md
- docs/development/installation.md
- docs/development/mernis-test-data.md
- docs/development/rake-task.md
- docs/development/test-coverage.md
- docs/development/third-parties.md
- docs/git/branch.md
- docs/git/commit.md
- docs/git/issue.md
- docs/git/pull-request.md
- docs/git/review.md
- docs/how-to/arel-queries.md
- docs/how-to/navigate-units.md
- docs/how-to/navigate-users.md
- docs/ops/dokku.md
- docs/style/validations.md
- lib/tasks/pr.rake
**Bu PR'in yaptığı işi/değişikliği ve bu işi/değişikliği neden yaptığını açıklayın**
Bu PR geliştirme süreçlerinde sıkça karşılaşmaya başladığımız özensiz yazılmış commit mesajı, hatalı PR başlığı, geliştirme ortamının düzgün kurulmamış olması gibi sorunlara son vermek adına yazılmış detaylı dokümanları içerir. Bu PR'le birlikte Wiki sayfaları tamamen kaldırılmış olup tüm dokümantasyon /docs dizinine alınmıştır.
> Bu PR'in branch'ine gidip linklere tıklarsanız hata mesajı alabilirsiniz, çünkü branch henüz merge edilmediği için bağlantılar boşa düşüyor - merge edildiğinde düzelecek.
**İlgili iş kayıtları**
#218.
**Kapatılacak iş kayıtları**
Closes #218.
**Geliştirici bilgisayarı**
Bu PR merge edildiğinde, projeyi `bundle install` yaptıktan ve proje dizinine düştükten sonra tüm …
> Add guides and developer docs

- .circleci/config.yml
- .circleci/parallel_workflow.yml
- .circleci/sequential_basic_workflow.yml
- Gemfile
- Gemfile.lock
Gemfile'ın `development` grubu altında tanımlanan GEM'lerin CI veya production'da bundle edilmesine ihtiyaç olmamalı. Bu PR:
- `test` ortamında da kullanılan `bundler-audit`'i `development`'tan `development-test`'e taşır.
- `test` ortamında kullanılmayan `pry-rails`'i `development-test`'ten `development`'a taşır.
- Henüz kullanımda olmayan `capybara`, `chromedriver-helper`, ve `selenium-webdriver` boşuna bundle edilmemeleri için comment-out eder.
- CircleCI konfigürasyonunu `development` bağımlılıklarını bundle etmeyecek şekilde düzenler.
[//]: # (Bu PR ile ilişkili iş …
> Reorganize gemfile

- app/controllers/account/positions_controller.rb
- app/models/accounts/position.rb
- app/views/account/duties/show.html.erb
- app/views/account/positions/_form.html.erb
- config/locales/models/account/en.yml
- config/locales/models/account/tr.yml
- db/migrate/20180817060355_add_start_date_and_end_date_to_position.rb
- db/schema.rb
- test/fixtures/positions.yml
- test/models/accounts/position_test.rb
Kişilerin yöneticilik görevi ne zaman başladı, ne zaman bitti bilgisini tutulmuyordu. Bu PR ile birlikte Position modeline görev başlangıç ve bitiş tarihi girilebilecek alanlar eklendi.
#163 
Fixes: #163 
Closes: #163 
[//]: # (Bu PR merge edildiğinde veritabanı üzerinde …
> Add start date and end date to position

- Gemfile
- Gemfile.lock
Upgrade:
- aws-sdk-core from 3.24.1 to 3.25.0
- aws-sdk-s3 from 1.17.0 to 1.17.1
- pg from 1.1.1 to 1.1.2
- rails from 5.2.0 to 5.2.1
Yok.
[//]: # (Bu PR merge edildiğinde sunucular üzerinde bir değişiklik - paket kurulması, buildpack eklenmesi vb. - yapılması gerekecekmi, açıklayın.)
Yok.
> Upgrade bundler dependencies

- test/config/database_config_test.rb
Test yaparken düzeltilmesi unutulan ve hasbelkader çalışan kodu düzelt
#239 ve #240 (kapalı)
Yok
Yok
Yok
> Artık kodu düzelt

- Vagrantfile
- config/locales/layouts/application/tr.yml
- docs/development/installation.md
- docs/development/rake-task.md
- docs/git/branch.md
- docs/git/commit.md
- docs/git/issue.md
- docs/git/pull-request.md
- docs/how-to/navigate-units.md
- docs/ops/dokku.md
- docs/style/validations.md
Minör düzeltmeler/iyileştirmeler (dokümantasyon ağırlıklı)
Yok
Yok
Yok
Yok
> Minor tweaks

- app/views/users/_addresses.html.erb
- config/routes.rb
- test/controllers/users_controller_test.rb
- #91'de belirtilen panelden kullanıcı oluşturulamaması sorununu çözer.
- users_controller için controller testlerini ekler.
#91
Fixes #91.
[//]: # (Bu PR merge edildiğinde veritabanı üzerinde herhangi bir değişiklik -migration, seed, add/drop vb.- yapılması gerekecek mi …
> Manage users from ui

- config/initializers/rollbar.rb
Rollbar'ı yalnızca production ve beta ortamında çalışacak şekilde konfigüre eder.
#247 
Closes #247.
N/A …
> Disable rollbar in development and test

- .rubocop.yml
- app/models/accounts/employee.rb
- app/models/accounts/position.rb
- app/validators/duty_validator.rb
- app/validators/employee_validator.rb
- app/validators/position_validator.rb
- app/views/account/duties/_form.html.erb
- app/views/account/positions/_form.html.erb
- config/locales/validators/en.yml
- config/locales/validators/tr.yml
- test/fixtures/positions.yml
- test/models/accounts/duty_test.rb
- test/models/accounts/employee_test.rb
- test/models/accounts/position_test.rb
#166 'da belirtilen kısıtlamalar ışığında EmployeeValidator ve DutyValidator yeniden düzenlendi ve PositionValidator oluşturuldu. 
Position modeline:
- Validasyon için `active` scope ve `active?` method eklendi.
- Mevcut durumda aynı birimde aynı görev kaydı pasif olsa dahi oluşturulamıyordu. Bu yüzden `duty_id,` `administrative_function_id` uniqueness validasyonuna Duty modeli örnek alınarak `start_date` eklendi.
Yapılan değişikliklere göre:
Employee
- Bir kullanıcının birden çok aktif ünvanı olamaz.
- Bir kullanıcının birden çok farklı pasif ünvanı olabilir.
Duty
- Başlangıç tarihi bitiş tarihinden önce olmalıdır.
- Bir kullanıcının sadece bir adet kadrolu (geçici olmayan) aktif kaydı olabilir.
- Bir …
> Duty, Employee ve Position validasyonlarını düzenle

- app/controllers/concerns/last_update_from_mernis.rb
- app/controllers/users_controller.rb
- app/views/users/_addresses.html.erb
- app/views/users/_identities.html.erb
- config/locales/models/user/en.yml
- config/locales/models/user/tr.yml
- config/routes.rb
- db/schema.rb
Kullanıcı profillerinde adres ve kimlik bilgileri sayfalarına MERNİS butonları eklendi.
#144 
Closes #144 
NA
**Sistem/Ops …
> Kullanıcı profillerine MERNİS butonları ekle

- .github/ISSUE_TEMPLATE/use-case.md
Product ekibinin hazırladığı use case'ler için açılacak issue'lar için issue template'ini tanımlar.
[//]: # …
> Use case issue template'i oluştur

- .circleci/config.yml
Bu düzenlemeyle develop dalı dokku'ya otomatik deploy edilecektir.
develop dalı https://dev.nokul.omu.sh adresinden erişilebilir olacaktır.
N/A
N/A
nokul beta'daki veritabanı aşağıdaki komutla klonlandı.
`dokku postgres:clone nokul-database nokul-develop-database`
uygulama nokul beta ile aynı sunucuda bulunmakta olup, uygulama ismi `nokul-develop` olarak belirlenmiştir.
domain: https://dev.nokul.omu.sh
**Ek Bilgiler:**
Geliştirici anahtarları bu sunucuya eklendiğinden log takip etme gibi özellikleri dokku istemcisi aracılığıyla kullanabilirler.
> Develop dalı otomatik deploy edilsin

- .circleci/config.yml
Develop dalı şimdilik otomatik deploy edilmesin. Bunun nedeni deploy sürelerinin çok uzun olması. Dockerfile tabanlı deploy'a geçene kadar bu iş ertelenmeli.
N/A
N/A
N/A
N/A
**Ek içerik:**
N/A
> Develop dalı şimdilik otomatik deploy edilmesin

- app/assets/javascripts/application.js
- app/assets/javascripts/helpers/dynamic_select.js
Dinamik select box oluştururken gerekli event'ların ve ajax isteklerinin kolaylıkla oluşturulması sağlayan bir javascript temelli yardımcı metodları içerir.
N/A
N/A
N/A
[//]: # (Bu PR merge edildiğinde sunucular üzerinde bir değişiklik - paket kurulması, buildpack eklenmesi vb. - yapılması gerekecekmi, açıklayın.)
**Ek içerik:**
**Kullanım Örneği:**
```erb
<div class='form-group col-sm-6'>
<%= select_tag(:country_id, options_from_collection_for_select(Country.all, :id, :name), class: 'form-control') %>
</div>
<div class='form-group col-sm-6'>
<%= select_tag(:city_id, [], …
```
> Dinamik selectbox oluşturmak için js helper ekle

- app/controllers/registration_documents_controller.rb
- app/models/document.rb
- app/models/registration_document.rb
- app/models/unit.rb
- app/views/registration_documents/_form.html.erb
- app/views/registration_documents/edit.html.erb
- app/views/registration_documents/index.html.erb
- app/views/registration_documents/new.html.erb
- app/views/registration_documents/show.html.erb
- app/views/units/show.html.erb
- config/locales/models/documents/tr.yml
- config/locales/models/registration_documents/en.yml
- config/locales/models/registration_documents/tr.yml
- config/locales/models/units/en.yml
- config/locales/models/units/tr.yml
- config/routes.rb
- db/migrate/20180919072617_create_registration_documents.rb
- db/schema.rb
- test/controllers/registration_documents_controller_test.rb
- test/fixtures/registration_documents.yml
- test/models/registration_document_test.rb
Programa kayıtlanma için gerekli olan belgelerin ilgili dönem ve program ile ilişkilendirilebilmesini sağlar.
Birim sayfasında "Gerekli Belgeler" linkinden o birim için geçmişte ve mevcut dönemde kayıtlanma için gerekli olan belgeler listelenir.
**Şimdilik tüm birimler için belge eklenebilir. Daha sonra (başka bir çalışma ile çakışacağından sonraya bırakıldı) yanlızca birim türü program olan birimler için ekleme yapılabilecek şekilde düzenleme yapılacaktır.**
#309
Closes: #309 
Registration Document için migration eklendi:
rails db:migrate
N/A
> Registration Document için model controller view ekle

- app/controllers/concerns/reference_resource.rb
- app/controllers/references/unit_types_controller.rb
- app/controllers/units_controller.rb
- app/models/references/unit_status.rb
- app/models/references/unit_type.rb
- app/models/unit.rb
- app/views/references/unit_types/_form.html.erb
- app/views/references/unit_types/index.html.erb
- config/locales/models/references/en.yml
- config/locales/models/references/tr.yml
- db/migrate/20180919115101_add_group_to_unit_type.rb
- db/schema.rb
- test/fixtures/unit_types.yml
- test/fixtures/units.yml
- test/models/references/unit_status_test.rb
- test/models/references/unit_type_test.rb
- test/models/unit_test.rb
- Aktif birimleri scope yardımı ile sorgulayabilmek için `Unit` ve `UnitStatus` modellerine gerekli scope'lar eklendi.
- Birimlerin türlere göre sorgulamalarının daha genel ve kolay hale getirilmesi sağlandı.
- Birim türlerinin gruplanması sağlandı.
- Unit modelinde scope düzenlemesi yapıldı.
N/A
Closes #328 
Yeni bir migration eklendi. `db:migrate` işleminin yapılması gerekli.
N/A
> Birim modeli için iyileştirmeler yap

- config/environments/production.rb
JS şablonlarında backtick kullanımı başta olmak üzere ES6 sözdiziminin desteklenmesi için Uglifier'ın doğru yapılandırması gerekiyor.  Önerilen Rails yapılandırması: https://github.com/lautis/uglifier#rails
#331 
Closes #331 
N/A
N/A
> Enable ES6 syntax support for Uglifier

- app/controllers/registration_documents_controller.rb
- app/views/units/show.html.erb
- test/fixtures/registration_documents.yml
Kayıtlanma belgeleri tüm unit'ler ile ilişkilendirilebiliyordu. Değişiklik yalnızca program türündeki birimlerle eşleştirilebilmesini sağlar.
#329 
Closes #329
N/A
N/A
> Belgelerin yalnızca programlarla ilişkilendirilmesini sağla

- app/jobs/osym/import_prospective_students_job.rb
ProspectiveStudentJob import edilirken progress_bar'ın sebep olduğu hata düzeltildi.
N/A
N/A
[//]: # (Bu PR …
> Fix readlines issue in prospective students job

- Dockerfile
Rollbar hatasını düzeltir.
Fixes #765
N/A
N/A
**Ek içerik:**
Test edilmedi.
> Upgrade deployment container to 1.13.1 which fixes #765 (Rollbar error)

- app/controllers/course_management/available_course_groups_controller.rb
- app/models/available_course_group.rb
- app/validators/available_course_lecturer_validator.rb
- app/validators/course_evaluation_type_validator.rb
- app/views/course_management/available_course_groups/_form.html.erb
- app/views/course_management/available_course_groups/_js.html.erb
- app/views/course_management/available_course_groups/_lecturer_fields.html.erb
- config/locales/controllers/course_management/available_course_groups.en.yml
- config/locales/controllers/course_management/available_course_groups.tr.yml
- test/controllers/course_management/available_course_groups_controller_test.rb
- test/controllers/course_management/curriculums_controller_test.rb
- test/fixtures/curriculums.yml
- Açılan derse grup tanımlarken en az 1 öğretim elemanı eklenmesi zorunlu hale getirildi. Hem backend hem de frontend tarafında bu engelleme sağlandı.
- Ders grubundaki öğretim elemanlarından birinin **Grup Koordinatörü** olması zorunlu hale getirildi.
- Değerlendirme türündeki ölçme kriterlerinin toplam yüzdeliği her koşulda 100'e eşit olması sağlandı.
Closes #718 
Fixes #757 
[//]: # (Bu PR merge edildiğinde hangi iş kayıtları kapatılacak ise `Closes`, `Fixes` gibi anahtar kelimeler ile birlikte ID numaralarını listeleyin. Kapatılmayan ancak referans verilecek iş …
> Açılan ders gruplarının öğretim elemansız oluşturulmasını engelle

- config/application.rb
- config/database.yml
- docker-compose.yml
Rails'teki son değişikliklerden kaynaklanan veritabanı yapılandırma hatası düzeltildi.
Closes #843 
N/A
N/A
> Database yapılandırmasını düzelt

- .rubocop.yml
- app/controllers/concerns/reference_resource.rb
- doc/development/installation.md
- lib/tasks/developer.rake
- lib/tasks/pull_request.rake
Geliştirici makinesinde:
- `RAILS_MASTER_KEY` (veya `config/master.key`) olup olmadığını
- `fit-commit`'in kurulu olup olmadığını
- NodeJS sürümünü
- PostgreSQL sürümünü
kontrol eden rake task'i ekler.
[//]: # (Bu PR merge edildiğinde hangi iş kayıtları kapatılacak ise `Closes`, `Fixes` gibi anahtar kelimeler ile birlikte ID numaralarını listeleyin. Kapatılmayan ancak referans verilecek iş kayıtları için `References` anahtar kelimesini kullanın.)
- References #853 
[//]: # (Bu PR merge edildiğinde veritabanı üzerinde herhangi bir değişiklik …
> Add a rake task checking development machine prerequisities

- Gemfile
- Gemfile.lock
- `chromedriver-helper` ve `selenium-webdriver` GEM'lerini kaldırır, `webdrivers` GEM'ini ekler.
```
+--------------------------------------------------------------------+
|                                                                    |
|  NOTICE: chromedriver-helper is deprecated after 2019-03-31.       |
|                                                                    |
|  Please update to use the 'webdrivers' gem instead.                |
|  See https://github.com/flavorjones/chromedriver-helper/issues/83  |
|                                                                    | …
```
> Remove chromedriver-helper and selenium-webdriver, add webdrivers gem

- .gitallowed
- app/models/address.rb
- app/models/user.rb
- app/services/activation/student_activation_service.rb
- doc/git/commit.md
- lib/tasks/security.rake
- plugins/support/test/codification/memory_test.rb
- plugins/support/test/core_ext/class_test.rb
- plugins/tenant/common/.rubocop.yml
- plugins/tenant/common/lib/nokul/tenant.rb
- plugins/tenant/common/lib/nokul/tenant/api.rb
- plugins/tenant/common/lib/nokul/tenant/engine.rb
[git-secrets](https://github.com/awslabs/git-secrets) ile hassas verilerin depoya eklenmesini önlemeye çalışıyoruz.  Bu PR kapsamında:
- Üretilen false pozitiflerin göz ardı edilmesini sağlayan bir dosya ekle ( Geliştirme süreci boyunca dosyayı güncel tutalım.)
- Geliştirici dokümanlarını güncelle.
Fixes #853
N/A
N/A
> Git secrets desteği ekle

- app/controllers/account/activations_controller.rb
- app/controllers/first_registration/prospective_employees_controller.rb
- app/services/activation/activation_service.rb
- app/services/first_registration/prospective_service.rb
- config/locales/layouts/shared/sidebar_tr.yml
- test/services/activation/activation_service_test.rb
Aday personellerin hesabını aktifleştirebilmesi sağlandı.
Aday personel oluştururken formda gözükmeyen bazı hataların gösterilmesi sağlandı.
Closes #906 
[//]: # (Bu PR merge edildiğinde hangi iş kayıtları kapatılacak ise `Closes`, `Fixes` gibi anahtar kelimeler ile birlikte ID numaralarını listeleyin. Kapatılmayan ancak referans verilecek iş kayıtları için `References` anahtar kelimesini kullanın.)
N/A
[//]: # (Bu PR merge edildiğinde veritabanı üzerinde herhangi bir değişiklik -migration, seed, add/drop vb.- yapılması gerekecek mi …
> Aday personellerin hesap aktifleştirmesini sağla

- app/services/xokul/meksis.rb
- doc/app/xokul.md
PR, Xokul'a https://api.omu.sh tarafından sağlanan Meksis'i ekler.
Closes #932 
Teknik borç yok.
Veritabanına etkisi yok.
Sistem etkisi yok.
Ek içerik yok.
> Xokul istemcisine Meksis'i ekle

- app/assets/javascripts/application.js
- app/assets/javascripts/guest.js
- app/assets/javascripts/shared/intl_tel_input_utils.js
- app/assets/javascripts/shared/intl_tel_input_validation.js
- app/assets/stylesheets/application.scss
- app/controllers/account/registrations_controller.rb
- app/services/activation/activation_service.rb
- app/views/account/activations/_js.html.erb
- app/views/account/activations/new.html.erb
- app/views/account/registrations/_js.html.erb
- app/views/account/registrations/edit.html.erb
- config/initializers/assets.rb
- config/locales/gems/intl_tel_input/en.yml
- config/locales/gems/intl_tel_input/tr.yml
- package.json
- test/controllers/accounts/activation_controller_test.rb
- test/services/activation/activation_service_test.rb
- yarn.lock
- [intl-tel-input](https://github.com/jackocnr/intl-tel-input) kitaplığı eklendi.
- Telefon alanlarında client-side doğrulama aktive edildi.
Closes #945 
[//]: # (DİKKAT! …
> Telefon alanları için intl-tel-input kitaplığını kullan

- lib/tasks/static_analysis/all.rake
- lib/tasks/static_analysis/eslint.rake
PR,
- JavaScript için eslint görevi ekler
- Eklenen görevi CI'da etkinleştirir
Closes #965 
n/a
n/a
n/a
n/a
> JavaScript dosyaları için lint görevi ekle

- .dependabot/config.yml
PR,
- Dependabot için yapılandırma dosyası ekler
- Mevcut yapılandır haftalık olarak Ruby ve JavaScript bağımlılıklarını haftalık olarak günceller
N/A
Ucu çok açık olduğu için iş kaydını açmıyorum ancak ilerde bu ayarlar güncellenmeli. GitHub dependabot'u satın almış. Bu yüzden native bir özellik haline getirmeyi düşünüyorlar. `.dependabot/config.yml` gelecekte `.github/.dependabot.yml` gibi birşey olacak: https://github.com/dependabot/feedback/issues/575
N/A
N/A
N/A
> Dependabot yapılandırması ekle

- .github/CONTRIBUTING.md
Branch oluşturma dokümanı ile ilgili bağlantı bozukluğunu gidermek amacıyla gerçekleştirildi.
YOK
[//]: # (DİKKAT! TEKNİK BORÇ YOKSA AŞAĞIDAKİ SATIRI N/A İLE DEĞİŞTİRİN VEYA …
> CONTRIBUTING.md was updated for "branch link".

- .github/CONTRIBUTING.md
Katkı sunma rehberindeki bağlantıları günceller.
N/A
N/A
N/A
[//]: # (PR merge edildiğinde …
> Katkı sunma rehberini güncelle

- .rubocop_common.yml
- app/validators/employee_validator.rb
- doc/README.md
- plugins/support/.rubocop.yml
- plugins/support/lib/nokul/support/minitest/association_helper.rb
- plugins/tenant/common/.rubocop.yml
- plugins/tenant/omu/.rubocop.yml
Dokümandaki yazım hatasını düzeltir.
N/A
N/A
N/A
[//]: # (PR merge edildiğinde veritabanı …
> Yazım hatasını düzelt

- plugins/support/test/codification/random_numeric_codes_test.rb
Nadiren ortaya çıkan bir [test hatasını](https://travis-ci.com/omu/nokul/jobs/243906737#L869) düzeltir.
Fixes #1074 
N/A
N/A
N/A
> Fix an edge test case rarely occured

- app/views/meksis/buildings/index.pdf.erb
MEKSIS "Binalar" ekranından alınan PDF'teki asset yükleyememe sorununu çözer.
Fixes #1082 
n/a
n/a
n/a
n/a
> MEKSIS bina listesinden alınan PDF'teki asset yükleyememe sorununu düzelt

- app/services/xokul/connection.rb
- doc/app/xokul.md
- plugins/support/lib/nokul/support/rest_client.rb
PR,
- REST istemcisini refaktör eder
- Xokul servisinin istemcisini refaktör eder
Fixes #1079 
Fixes #1077 
Fixes #1076 
n/a
n/a
n/a
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)
> REST ve Xokul istemcisini refaktör et

- config/locales/controllers/account/settings.tr.yml
Şifre yerine parola kullanıldı.
N/A
N/A
[Teknik borç](../issues/new?labels=debt&template=debt.md)
N/A …
> Şifre yerine parola kullan

- app/controllers/account/registrations_controller.rb
Parola degisikliginden sonra devise kullaniciyi log-out yaptigi icin `after_action` calismiyordu, ilgili callback'i `before_action` ile degistirir.
Closes #1113 
- N/A
- N/A
> Run update_password_change_time with before_action

- config/locales/controllers/account/devise.tr.yml
- config/locales/controllers/account/passwords.tr.yml
- config/locales/controllers/account/unlocks.tr.yml
- config/locales/controllers/course_management/available_course_groups.tr.yml
- config/locales/controllers/course_management/available_courses.tr.yml
- config/locales/controllers/first_registration/prospective_employees.tr.yml
- config/locales/controllers/patron/assignments.tr.yml
- config/locales/models/account/tr.yml
- config/locales/models/user/tr.yml
Çevirilerde düzeltme yapar, yazım hatalarını düzeltir.
N/A
N/A
N/A
[//]: # (PR merge …
> Yazım hatalarını düzelt

- app/models/employee.rb
- test/fixtures/employees.yml
Pasif personelliğe sahip bir kişinin sicil numarası başka bir kişinin aktif personelliğinde kullanılabiliyordu. Personel sicil numaralarının kişiye özel olması sağlandı.
Fixes #1180 
N/A
[//]: # (Örnek: yeni paket kurulması, buildpack …
> Fix staff number validation

- db/migrate/20191111082956_remove_unique_constraint_from_buildings.rb
- db/structure.sql
MEKSİS binalarda koordinatlar için eklenen uniqueness validasyonunu kaldırır.
Fixes #1196 
n/a
`bin/rails db:migrate`
n/a
n/a
> Binalarda koordinatlar için uniqueness validasyonunu kaldır

- app/views/meksis/place_types/_search.html.erb
- app/views/meksis/place_types/index.html.erb
- config/locales/controllers/meksis/place_types.en.yml
- config/locales/controllers/meksis/place_types.tr.yml
PR,
- Mekan türlerinin indeks sayfasını herhangi bir builder kullanmadan oluşturur
- Çeviri dosyalarını buna göre düzenler
Fixes #1157 
n/a
n/a
n/a
n/a
> Mekan türlerinin indeks sayfası için builder kullanma

- Dockerfile
- app/controllers/application_controller.rb
- test/config/tenant_config_test.rb
- test/services/ldap/entity_test.rb
- Dockerfile'da default tenant acme yapıldı.
- Tenant testleri düzeltildi.
[//]: # (PR merge …
> Tenant değişikliği sonrası ortaya çıkan hataları düzelt

- config/locales/defaults/tr.yml
Çevirideki hatayı düzeltir.
[Teknik borç](../issues/new?labels=debt&template=debt.md)
N/A …
> Çeviri hatasını düzelt

- Gemfile
- Gemfile.lock
- app/models/prospective_employee.rb
- app/models/user.rb
- config/locales/errors/en.yml
- config/locales/errors/tr.yml
- test/models/user_test.rb
`email_address` GEM'ini `valid_email2` ile degistirir.
Closes #147 
- N/A
- N/A
> Replace email_address with valid_email2

- Gemfile
- app/models/prospective_employee.rb
- app/models/user.rb
- test/models/user_test.rb
- Rubocop'un verdiği hataları çözer.
- Kullanıcı testindeki email doğrulama kısmındaki hatayı çözer.
N/A
N/A
N/A …
> Fix rubocop offenses

- app/models/student.rb
- app/services/student_course_enrollment_service.rb
- test/models/student_test.rb
- test/services/student_course_enrollment_service_test.rb
- Sahte GANO değeri 1. sınıf 1. dönem öğrencisi için sıfır olacak şekilde yeninden düzenlendi.
- Eklenen `extra_ects` metotu ile yarıyıl için arttırılabilir AKTS miktarının hesaplanması yeniden düzenlendi.
Fixes #1278 
N/A
N/A
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)
> Arttırılabilr AKTS miktarı ve GANO hesaplamalarında düzeltme yap

- app/views/layouts/shared/_meta.html.erb
PR, master dalını develop ile günceller.
n/a
n/a
n/a
n/a
n/a
> Merge develop into master

- .gitallowed
`git secrets --scan` komutu hata veriyordu, düzeltildi. …
> Update .gitallowed list

- doc/app/sso.md
LLNG ve LDAP arasındaki bağlantının kopmasını engellemenin geçici çözümünü dokümanlara ekler.
[//]: # (DİKKAT! TEKNİK BORÇ YOKSA AŞAĞIDAKİ SATIRI N/A İLE DEĞİŞTİRİN VEYA …
> LemonLDAP dokümanı ekle

- lib/tasks/s3.rake
Dokku, deploy esnasında git dizinini kaldırıyor. Bu nedenle git'e bağlı işler çalışmıyor. PR, S3 görevindeki git'e bağlı işlemleri kaldırır.
n/a
n/a
n/a
n/a
n/a
> S3 görevinde git yerine Rails metodu kullan

- db/beta_seed/user.rb
- db/seeds.rb
seed aşamasında `SAMPLE_DATA=true` dendiğinde, TC'si 11_111_111_111 olan örnek bir kullanıcı ekler.
Yalnızca çalışma ortamına seed verisi ekleyecek.
[//]: # (PR merge edildiğinde sunucular …
> Örnek seed verilerine cezmi kullanıcısını ekle

- Gemfile
- Gemfile.lock
- app/jobs/rake_job.rb
- app/jobs/sidekiq_rake_job.rb
- config/initializers/sidekiq.rb
- config/schedule.yml
- doc/app/cron.md
[sidekiq-cron ](https://github.com/ondrejbartas/sidekiq-cron) gem'ini sisteme ekler.
Gem kullanımı gem'in sayfasından ya da `doc/app/cron.md` dosyasından öğrenilebilir.
Katkılarından dolayı @isubas'a teşekkürlerimi sunuyorum.
N/A
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)
> Sidekiq-cron gem'ini ekle

- test/system/wicked_pdf_test.rb
PR, sistemdeki `wkhtmltopdf` ile PDF üretimini test eder.
Closes #1254 
N/A
N/A
N/A
N/A
> PDF üretimini basitçe test et

- app/controllers/students_controller.rb
- app/models/student.rb
- app/models/student_grade.rb
- app/views/students/edit.html.erb
- app/views/user_management/users/_students.html.erb
- config/locales/models/user/en.yml
- config/locales/models/user/tr.yml
- db/migrate/20200317094504_add_stage_to_student.rb
- db/structure.sql
- test/fixtures/student_grades.yml
- test/fixtures/students.yml
- test/models/student_grade_test.rb
- test/models/student_test.rb
Öğrencinin hangi aşamada olduğu bilgisi artık belirlenebiliyor. Bu aşamalardan harç borcunun oluşturulmasında lazım olan "Yabancı dil hazırlık" aşaması için scope oluşturulmuştur. 
`Grade` modeli ile karışıklık yaşanmaması adına `stage` olarak kullandım.
`rails db:migrate`
N/A
> Öğrencinin hangi aşamada olduğunun belirlenmesini sağla

- app/models/unit.rb
- app/views/calendar_management/calendars/units.html.erb
- config/locales/controllers/calendar_management/calendars.en.yml
- config/locales/controllers/calendar_management/calendars.tr.yml
- lib/tasks/fix_data.rake
- test/models/unit_test.rb
- Akademik takvimlerin bölümlere de atanabilmesi sağlandı.
- Mevcut bulunan takvimlerdeki kayıp bölüm takvimi verileri için bir kullanımlık task eklendi (düzeltme arayüzden de yapılabilir, gereksiz görülürse kaldırılabilir).
`rails fix_data:department_calendars`
`rails fix_data:department_calendars`
> Akademik takvimin bölümlere atanabilmesini sağla

- app/models/unit.rb
- test/models/unit_test.rb
Ders açma işleminde aktif görevi olan kişilerin listede gösterilmesi sağlandı.
N/A
N/A
[//]: # (Ekran görüntüleri)
[//]: # (Örnek çözümler)
> Ders açarken aktif görevlendirmesi olanların listelenmesini sağla

- Gemfile
- Gemfile.lock
rack-oauth2 gem'inin sürümü yükseltildi.
> Upgrade rack-oauth2

- app/controllers/tuition_management/tuition_debts_controller.rb
- app/policies/tuition_management/tuition_debt_policy.rb
- test/policies/tuition_management/tuition_debt_policy_test.rb
- test/policies/tuition_management/tuition_policy_test.rb
Harç borcu oluşturma süreçlerine yetkilendirme eklendi.
N/A
N/A
> Harç borçlarına yetkilendirme ekle
